name = "TractableTreeDistributions"
uuid = "1ed903b1-d65e-4243-bae3-7d6e2e5f54a0"
authors = ["Tobia Ochsner <tobia.ochsner@hotmail.com>"]
version = "0.1.0"

[deps]
NewickTree = "b0a14db8-6308-4ebc-8917-f72cd81f5094"

[compat]
NewickTree = "0.3.1"
