name = "TractableTreeDistributions"
uuid = "1ed903b1-d65e-4243-bae3-7d6e2e5f54a0"
authors = ["Tobia Ochsner <tobia.ochsner@hotmail.com>"]
version = "0.1.0"

[deps]
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
PhyloNetworks = "1.0.0"
Test = "1.11.0"
